# Generated by Django 3.2.14 on 2022-08-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adaptor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsPolicy',
            fields=[
                ('policy_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=36)),
                ('version', models.CharField(max_length=20)),
                ('format', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'os_policy',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Roles', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='rolepermissions',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Role_permissions', 'verbose_name_plural': 'Role_permissions'},
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='RolePermissions', to='adaptor.role'),
        ),
    ]
