# Generated by Django 3.2.14 on 2022-08-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptor', '0002_auto_20220817_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ospolicy',
            options={'managed': False, 'verbose_name': 'OsPolicy', 'verbose_name_plural': 'OsPolicy'},
        ),
    ]
