# Generated by Django 3.2.14 on 2023-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptor', '0003_alter_ospolicy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALYPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=20)),
                ('policy_name', models.CharField(max_length=36)),
                ('version', models.CharField(max_length=20)),
                ('format', models.CharField(max_length=20)),
                ('policy_rules_addr', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ALYPolicy',
                'verbose_name_plural': 'ALYPolicy',
                'db_table': 'aly_policy',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='sort_order',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
