version: 2
jobs:
  build:
    working_directory: ~/policy-machine-core
    machine: true
    steps:
      - checkout # check out source code to working directory
      - run: mvn dependency:go-offline # gets the project dependencies
      - run: mvn package # run the actual tests